repos:
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0  # Update this to the latest version or the one compatible with Python 3.10
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --show-traceback, --explicit-package-bases]